[package]
name = "batsat"
version = "0.0.2"
authors = ["Simon Cruanes", "Masaki Hara <ackie.h.gmai@gmail.com>"]
description = "SAT solver in Rust"
homepage = "https://github.com/c-cube/batsat"
repository = "https://github.com/c-cube/batsat"
readme = "README.md"
keywords = ["sat"]
categories = ["algorithms"]
license = "MIT"

[dependencies]

log = {version="0.4", optional=true}

